// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Vir1GMVUwvAwKOsl-ln54CNo9-4j4xg',
    appId: '1:655776751047:web:afa82b71bb1eaacec44de2',
    messagingSenderId: '655776751047',
    projectId: 'bookly-bbbb8',
    authDomain: 'bookly-bbbb8.firebaseapp.com',
    storageBucket: 'bookly-bbbb8.firebasestorage.app',
    measurementId: 'G-4J8W6E1E6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkPtpJmA9nL31mV8alUFqSif0Vuss_p7s',
    appId: '1:655776751047:android:60467857b9c65930c44de2',
    messagingSenderId: '655776751047',
    projectId: 'bookly-bbbb8',
    storageBucket: 'bookly-bbbb8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Vir1GMVUwvAwKOsl-ln54CNo9-4j4xg',
    appId: '1:655776751047:web:869be9960982f7d9c44de2',
    messagingSenderId: '655776751047',
    projectId: 'bookly-bbbb8',
    authDomain: 'bookly-bbbb8.firebaseapp.com',
    storageBucket: 'bookly-bbbb8.firebasestorage.app',
    measurementId: 'G-XEH5FYHQVT',
  );
}
